### ISSUE TITLE
Some shows have `episode title | CR123` and some don't

### ISSUE THREAD

**Issue by IronicBadger** [selfhostedshow/show-notes#11]
Some shows have a nice `{{ episode_title }} | {{ show_shortname}}{{ep_num}}` and others don't. Coder has this for example and it makes search much better as you can identify which show a global search - er - search, belongs to.

**Comment by IronicBadger** [comment]
<img width="521" alt="Screen Shot 2021-07-22 at 22 38 56" src="https://user-images.githubusercontent.com/2773080/126731624-9d5b6994-6327-47ae-bfcd-9942e3373450.png">

**Comment by RealOrangeOne** [comment]
Yeah the way titles are structured has changed over the years, and a little between shows. Need to run through them all and add support.

Also make sure show notes / sponsors are picked up correctly.

**Comment by IronicBadger** [comment]
Titles should be `026: The Trouble with Docker | LUP 26` for example.

**Comment by IronicBadger** [comment]
Final result. 👍 

![image](https://user-images.githubusercontent.com/2773080/127167716-9413b39f-4419-41c7-a4f2-6b9e27fbeb9a.png)
