### ISSUE TITLE
Certain parts of the site 404

### ISSUE THREAD

**Issue by Diacius** [selfhostedshow/show-notes#14]
If I try to select self hosted it takes me [here](https://notes.jupiterbroadcasting.com/self-hosted/) this returns a 404 error. And on Linux unplugged loads of the episodes 404. Is this unmaintained?

**Comment by ironicbadger** [comment]
Last nights CI failed for some reason. Unmaintained! How rude! 😉

**Comment by Diacius** [comment]
I’m so sorry, i was slightly confused as to how it said there was a commit a few hours ago, but that the whole site was broken!
