### ISSUE TITLE
Add Office Hours show

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#17]
Seems [Office Hours](https://www.officehours.hair/) isn't part of the search, and should be added if deemed appropriate considering potential search functionality to be integrated into the new [JB Site](https://github.com/JupiterBroadcasting/jupiterbroadcasting.com) and [Scraper](https://github.com/JupiterBroadcasting/show-scraper)

**Comment by ironicbadger** [comment]
#21
