### ISSUE TITLE
JSON feed for linuxunplugged.com is invalid

### ISSUE THREAD

**Issue by RealOrangeOne** [selfhostedshow/show-notes#23]
Previously, `linuxunplugged.com/json` emitted a JSON feed. At some point recently, this stopped being true, and instead it redirects to `feeds.jupiterbroadcasting.com/lup`, which is an XML RSS feed. This makes sense as a redirect target for linuxunplugged.com/rss`, but not for `/json`. 

The other show feeds all work fine, it's just LUP.

I don't have access to Fireside to properly suggest why this changed and what we need to change to get the JSON feed back.

**Comment by RealOrangeOne** [comment]
Because one feed fails, this means the entire site isn't being updated correctly.

**Comment by ironicbadger** [comment]
Fixed by #31
