### ISSUE TITLE
Menu - Show names uncapitalized, incorrectly spelled

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#24]
Show names in the menu are currently uncapitalized, i.e. sentence case. Some are also missing correct all-caps or hyphens.

![image](https://github.com/selfhostedshow/show-notes/assets/7018928/a9556027-59af-4988-8e83-11cccace309a)

Should be:

- [ ] `Coder radio` -> Coder Radio
- [ ] `Jupiter extras` -> Jupiter Extras
- [ ] `Linux action news` -> Linux Action News
- [ ] `Linux unplugged` -> LINUX Unplugged (note the ALLCAPS)
- [ ] `Office hours` -> Office Hours
- [ ] `Self hosted` -> Self-Hosted (note the dash)

Also appears:
![image](https://github.com/selfhostedshow/show-notes/assets/7018928/d7542f6a-a756-4201-a2f1-e4dd4fe855e3)

**Comment by ironicbadger** [comment]
mkdocs doesn't provide a way to fix this without hard coding the nav which I don't want to do given that as it stands new shows are auto added.
