### ISSUE TITLE
Extras - show names containing `:` are truncated

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#25]
Some show names containing `:` are truncated, likely over-aggressive grep-ing:

![image](https://github.com/selfhostedshow/show-notes/assets/7018928/0ede7be1-62b5-43df-85cb-e65827316532)
![image](https://github.com/selfhostedshow/show-notes/assets/7018928/46240f48-3ffd-478c-8f7f-95bfe77dd60f)

![image](https://github.com/selfhostedshow/show-notes/assets/7018928/64014a73-c7c7-4389-8b9b-31b563e59f90)

https://notes.jupiterbroadcasting.com/jupiter-extras/2019/episode-012/
https://notes.jupiterbroadcasting.com/jupiter-extras/2020/episode-045/

- [ ] should likely check all other shows...

**Comment by ironicbadger** [comment]
@RealOrangeOne do you have a moment to look at this possibly?

**Comment by ironicbadger** [comment]
Not resolved - see https://github.com/selfhostedshow/show-notes/blob/main/docs/jupiter-extras/2019/episode-012.md

**Comment by ironicbadger** [comment]
Thanks 🧡
