### ISSUE TITLE
Office Hours - menu item leads to EP 001, not landing page

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#28]
Menu item for Office Hours leads to `https://notes.jupiterbroadcasting.com/office-hours/2022/episode-001/` not the expected `https://notes.jupiterbroadcasting.com/office-hours/`

Also, `https://notes.jupiterbroadcasting.com/office-hours/` is `403 Forbidden`.

Office Hours should have a nice landing page like https://notes.jupiterbroadcasting.com/linux-unplugged/ and the menu item should lead there.

**Comment by ironicbadger** [comment]
#33 fixed
