### ISSUE TITLE
scraper - LUP, Coder, SSH not being scraped, i.e. missing episodes

### ISSUE THREAD

**Issue by gerbrent** [selfhostedshow/show-notes#29]
LUP 553 onward are missing from notes.jupiterbroadcasting.com, 
Coder 561 onward aswell.

Likely due to the recent RSS changes?

https://notes.jupiterbroadcasting.com/linux-unplugged/
https://notes.jupiterbroadcasting.com/coder-radio/

**Comment by gerbrent** [comment]
SSH > 118 also missing...

**Comment by RealOrangeOne** [comment]
I think this is caused by https://github.com/selfhostedshow/show-notes/issues/23

**Comment by gerbrent** [comment]
hmm, but https://selfhosted.show/json still seems fine and json as expected..

**Comment by ironicbadger** [comment]
Fixed by #31
